### ISSUE TITLE
支持 Superset Backend

### ISSUE THREAD

**Issue by mofanxjw** [aliyun/aliyun-odps-python-sdk#183]
在时间粒度字段下拉选不到时间单位，例如秒，分钟，小时，天，周等。
![image](https://user-images.githubusercontent.com/110454424/182325512-100a145e-581d-497d-bfdb-e3ed594fb201.png)

**Comment by wjsi** [comment]
有 error message 么？否则没法定位问题

**Comment by Menniti** [comment]
hello @mofanxjw, 
I`m having issues to connect into maxcompute use superset sqlalchemy
Do you mind to share your connection configuration ?
I have received error because I can`t setup this hint: 'odps.sql.hive.compatible=true'

![image](https://user-images.githubusercontent.com/15658494/187798613-a18f0448-a684-449a-982c-a13bc31eb900.png)

I would like to know how have you overcome this issue
Thanks
